env:
  MAVEN_VERSION: 3.9.2
jobs:
  build:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    name: Build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout liquibase-pro
      uses: actions/checkout@v4
      with:
        path: liquibase-pro
        ref: ${{ inputs.branch }}
        repository: liquibase/liquibase-pro
        token: ${{ secrets.BOT_TOKEN }}
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: maven-settings-xml-action
      uses: whelk-io/maven-settings-xml-action@v22
      with:
        plugin_repositories: "[\n  {\n    \"id\": \"file-replacer-maven-plugin\",\n\
          \    \"url\": \"https://maven.pkg.github.com/StevenMassaro/file-replacer-maven-plugin\"\
          ,\n    \"releases\": {\n      \"updatePolicy\": \"always\",\n      \"enabled\"\
          : \"true\"\n    },\n    \"snapshots\": {\n      \"enabled\": \"true\",\n\
          \      \"updatePolicy\": \"always\"\n    }\n  }\n]\n"
        repositories: "[\n  {\n    \"id\": \"liquibase\",\n    \"url\": \"https://maven.pkg.github.com/liquibase/liquibase\"\
          ,\n    \"releases\": {\n      \"enabled\": \"false\"\n    },\n    \"snapshots\"\
          : {\n      \"enabled\": \"true\",\n      \"updatePolicy\": \"always\"\n\
          \    }\n  },\n  {\n    \"id\": \"liquibase-pro\",\n    \"url\": \"https://maven.pkg.github.com/liquibase/liquibase-pro\"\
          ,\n    \"releases\": {\n      \"enabled\": \"false\"\n    },\n    \"snapshots\"\
          : {\n      \"enabled\": \"true\",\n      \"updatePolicy\": \"always\"\n\
          \    }\n  }\n]\n"
        servers: "[\n  {\n    \"id\": \"liquibase\",\n    \"username\": \"liquibot\"\
          ,\n    \"password\": \"${{ secrets.LIQUIBOT_PAT }}\"\n  },\n  {\n    \"\
          id\": \"liquibase-pro\",\n    \"username\": \"liquibot\",\n    \"password\"\
          : \"${{ secrets.LIQUIBOT_PAT }}\"\n  },\n  {\n    \"id\": \"file-replacer-maven-plugin\"\
          ,\n    \"username\": \"liquibot\",\n    \"password\": \"${{ secrets.LIQUIBOT_PAT\
          \ }}\"\n  }\n]\n"
    - continue-on-error: true
      name: Set up Maven
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: ${{ env.MAVEN_VERSION }}
    - continue-on-error: true
      name: Set version
      run: 'cd liquibase-pro/liquibase-azure-deps && mvn versions:set -DnewVersion=${{
        inputs.liquibase-version }}

        '
    - continue-on-error: true
      name: Build & Test
      run: 'cd liquibase-pro/liquibase-azure-deps && mvn -B clean package

        '
    - continue-on-error: true
      name: Archive Modules
      uses: actions/upload-artifact@v3
      with:
        name: liquibase-pro-azure-artifacts
        path: liquibase-pro/liquibase-azure-deps/target/liquibase-azure-deps-${{ inputs.liquibase-version
          }}.jar
name: Build Azure Uber jar
on:
  repository_dispatch:
    types: trigger-ga___build-azure-uber-jar.yml
