jobs:
  delete-package:
    name: Delete Github Package for Branch
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: version
      uses: castlabs/get-package-version-id-action@v2.2
      with:
        version: ${{ github.event.ref }}-SNAPSHOT
    - continue-on-error: true
      if: ${{ steps.version.outputs.ids != '' }}
      uses: actions/delete-package-versions@v5
      with:
        min-versions-to-keep: 0
        package-type: maven
        package-version-ids: ${{ steps.version.outputs.ids }}
name: Cleanup on Branch Delete
on:
  repository_dispatch:
    types: trigger-ga___cleanup-branch-builds.yml
