jobs:
  delete-package:
    name: Delete Github Packages for Master/Main
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/delete-package-versions@v5
      with:
        ignore-versions: ^DAT-.*-SNAPSHOT$
        min-versions-to-keep: 0
        package-name: ${{ matrix.packages_to_delete }}
        package-type: maven
    strategy:
      matrix:
        packages_to_delete:
        - org.liquibase.liquibase-core
        - org.liquibase.liquibase-extension-testing
        - org.liquibase.liquibase-integration-tests
        - org.liquibase.liquibase-maven-plugin
        - org.liquibase.liquibase-cdi-jakarta
        - org.liquibase.liquibase-cdi
        - org.liquibase.liquibase
name: Cleanup Master Builds on Release Published
on:
  repository_dispatch:
    types: trigger-ga___cleanup-master-builds.yml
