jobs:
  fossa:
    secrets: inherit
    uses: liquibase/build-logic/.github/workflows/fossa_ai.yml@main
    with:
      check_ai_generated_code: true
      check_snippets: true
      generate_sbom: true
name: FOSSA License Compliance and Security Check
on:
  repository_dispatch:
    types: trigger-ga___fossa_ai.yml
