jobs:
  create_draft_release_master_branch:
    permissions:
      contents: write
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_DRAFTER_TOKEN }}
      if: github.ref == 'refs/heads/master'
      name: Create Draft Release (Master)
      uses: release-drafter/release-drafter@v6
      with:
        config-name: release-drafter-master.yml
name: Release Drafter
on:
  repository_dispatch:
    types: trigger-ga___release-drafter.yml
permissions:
  contents: read
