jobs:
  automated-os-extensions-release:
    secrets: inherit
    uses: liquibase/build-logic/.github/workflows/os-extension-automated-release.yml@v0.7.8
    with:
      version: ${{ inputs.version }}
name: Release Extensions
on:
  repository_dispatch:
    types: trigger-ga___release-extensions.yml
