jobs:
  urlcheck:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Check URLs
      uses: urlstechie/urlchecker-action@master
      with:
        force_pass: false
        include_files: url-test.md
        print_all: false
        retry_count: 2
        timeout: 5
        verbose: true
    - continue-on-error: true
      env:
        MSG_MINIMAL: actions url
        SLACK_CHANNEL: team-liquibase-foundation
        SLACK_COLOR: ${{ job.status }}
        SLACK_ICON_EMOJI: ':liquibase:'
        SLACK_LINK_NAMES: true
        SLACK_MESSAGE: '${{ github.job }}: ${{ job.status }} @here'
        SLACK_USERNAME: liquibot
        SLACK_WEBHOOK: ${{ secrets.SNYK_LIQUIBASE_SLACK_WEBHOOK }}
      if: ${{ failure() }}
      name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
name: Liquibase Url Prerequisites Check
on:
  repository_dispatch:
    types: trigger-ga___url-check.yml
