jobs:
  deploy-ephemeral-cloud-infra:
    secrets: inherit
    uses: liquibase/build-logic/.github/workflows/ephemeral-cloud-infra.yml@main
    with:
      deploy: true
      snowflake_oss: true
  destroy-ephemeral-cloud-infra:
    if: always()
    needs:
    - deploy-ephemeral-cloud-infra
    - snowflake-its
    secrets: inherit
    uses: liquibase/build-logic/.github/workflows/ephemeral-cloud-infra.yml@main
    with:
      destroy: true
      snowflake_oss: true
      stack_id: ${{ needs.deploy-ephemeral-cloud-infra.outputs.stack_id }}
  run-slack-notification:
    if: failure()
    needs:
    - snowflake-its
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Dispatch event to build-logic repository
      uses: peter-evans/repository-dispatch@v3
      with:
        client-payload: '{"repository": "${{ github.repository }}", "branch": "${{
          github.ref }}", "sha": "${{ github.sha }}", "server_url": "${{ github.server_url
          }}", "run_id": "${{ github.run_id }}"}'
        event-type: test-failure
        repository: liquibase/build-logic
        token: ${{ secrets.LIQUIBOT_PAT_GPM_ACCESS }}
  snowflake-its:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    name: Run Snowflake Cloud integration tests
    needs: deploy-ephemeral-cloud-infra
    permissions:
      contents: read
      id-token: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up Java
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: Set up Maven settings.xml
      uses: whelk-io/maven-settings-xml-action@v22
      with:
        repositories: "[\n  {\n    \"id\": \"liquibase\",\n    \"url\": \"https://maven.pkg.github.com/liquibase/liquibase\"\
          ,\n    \"releases\": {\n      \"enabled\": \"false\"\n    },\n    \"snapshots\"\
          : {\n      \"enabled\": \"true\",\n      \"updatePolicy\": \"always\"\n\
          \    }\n  },\n  {\n    \"id\": \"liquibase-pro\",\n    \"url\": \"https://maven.pkg.github.com/liquibase/liquibase-pro\"\
          ,\n    \"releases\": {\n      \"enabled\": \"false\"\n    },\n    \"snapshots\"\
          : {\n      \"enabled\": \"true\",\n      \"updatePolicy\": \"always\"\n\
          \    }\n  }\n]\n"
        servers: "[\n  {\n    \"id\": \"liquibase-pro\",\n    \"username\": \"liquibot\"\
          ,\n    \"password\": \"${{ secrets.LIQUIBOT_PAT }}\"\n  },\n  {\n    \"\
          id\": \"liquibase\",\n    \"username\": \"liquibot\",\n    \"password\"\
          : \"${{ secrets.LIQUIBOT_PAT }}\"\n  }\n]\n"
    - continue-on-error: true
      name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        role-to-assume: ${{ secrets.AWS_DEV_GITHUB_OIDC_ROLE_ARN_BUILD_LOGIC }}
    - continue-on-error: true
      name: Get LIQUIBASEOSS secrets
      uses: aws-actions/aws-secretsmanager-get-secrets@v2
      with:
        secret-ids: 'LIQUIBASEOSS_USERNAME, liquibaseoss_usrname

          LIQUIBASEOSS_PASSWORD, liquibaseoss_pwd

          '
    - continue-on-error: true
      name: Run tests
      run: "./mvnw -B \"-DtrimStackTrace=false\" \\\n  \"-Dliquibase.sdk.testSystem.test=snowflake\"\
        \ \\\n  \"-Dliquibase.sdk.testSystem.snowflake.url=jdbc:${{ secrets.LIQUIBASEOSS_URL\
        \ }}&schema=PUBLIC&db=LIQUIBASEOSS\" \\\n  \"-Dliquibase.sdk.testSystem.snowflake.username=${{\
        \ env.LIQUIBASEOSS_USERNAME }}\" \\\n  \"-Dliquibase.sdk.testSystem.snowflake.password=${{\
        \ env.LIQUIBASEOSS_PASSWORD }}\" \\\n  \"-Dtest=*IntegrationTest,*ExecutorTest\"\
        \ \\\n  \"-DfailIfNoTests=false\" \\\n  \"-Dsurefire.failIfNoSpecifiedTests=false\"\
        \ \\\n  \"-Dsurefire.failIfNoTests=false\" \\\n  clean verify\n"
    - continue-on-error: true
      if: ${{ inputs.archive_test_results == 'true' }}
      name: Archive Test Results
      uses: actions/upload-artifact@v3
      with:
        name: liquibase-test-results-snowflake
        path: './**/target/surefire-reports

          ./**/target/site

          '
    timeout-minutes: 240
name: Weekly Integration Tests
on:
  repository_dispatch:
    types: trigger-ga___weekly-integration-tests.yml
